version: "3.9"
services:
  postgis:
    container_name: gis_postgis
    build: ./
    image: gis_postgis
    #restart: always
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres-passwd
    secrets:
      - postgres-passwd
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

secrets:
  postgres-passwd:
    file: ./postgres-passwd

volumes:
  pgdata:
    name: gis_pgdata
