default:
  connection_details:
    dbms: "sql server"
    server: "localhost"
    user: "user"
    password: "pass"
  cdm_schema: "OMOP_CDM.dbo"
  vocab_schema: "OMOP_CDM.dbo"
  gis_schema: "GIS.dbo"
  polygon_file_dir: "C:/gis_repo"
  temp_dir: "C:/gis_temp"
  default_epsg: "4326"
  convert_epsg: TRUE


